version: '3'
services:
#  axon-server:
#    container_name: axon-server
#    image: axoniq/axonserver
#    networks:
#      - mypay-network
#    ports:
#      - "8024:8024"
#      - "8124:8124"
#    volumes:
#      - axonserver-data:/axonserver/data
#      - axonserver-events:/axonserver/events
#      - axonserver-config:/axonserver/config:ro

  mysql:
    image: mysql
    networks:
      - mypay-network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=password

  membership-service:
    image: demo-membership-service:0.0.1-SNAPSHOT
    networks:
      - mypay-network
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      - AXON_AXONSERVER_SERVERS=axon-server:8124
      - AXON_SERIALIZER_EVENTS=jackson
      - AXON_SERIALIZER_MESSAGES=jackson
      - AXON_SERIALIZER_GENERAL=xstream
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/my_pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  banking-service:
    image: demo-banking-service:0.0.1-SNAPSHOT
    networks:
      - mypay-network
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      - AXON_AXONSERVER_SERVERS=axon-server:8124
      - AXON_SERIALIZER_EVENTS=jackson
      - AXON_SERIALIZER_MESSAGES=jackson
      - AXON_SERIALIZER_GENERAL=xstream
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/my_pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  money-service:
    image: demo-money-service:0.0.1-SNAPSHOT
    networks:
      - mypay-network
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    environment:
      - AXON_AXONSERVER_SERVERS=axon-server:8124
      - AXON_SERIALIZER_EVENTS=jackson
      - AXON_SERIALIZER_MESSAGES=jackson
      - AXON_SERIALIZER_GENERAL=xstream
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/my_pay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

#volumes:
#  axonserver-data:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: ${PWD}/axon-server-se/data
#  axonserver-events:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: ${PWD}/axon-server-se/events
#  axonserver-config:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: ${PWD}/axon-server-se/config

networks:
  mypay-network:
    driver: bridge
